site_name: nmBot Telegram 帮助文档
theme:
  name: material
  logo: https://websiteres.nmteam.xyz/producticon/nmBot/logo@128.png
  favicon: https://websiteres.nmteam.xyz/producticon/nmBot/logo@128.png
  language: zh
  palette:
    primary: blue

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/nm-Team/nmBot-Telegram-doc
copyright: Copyright 2022 nmTeam. All rights reserved. <br>nmBot Telegram Doc is licensed under the MIT License.

markdown_extensions:
  - attr_list
  - md_in_html
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - 首页: index.md
  - 在群组中使用 nmBot:
      - 设置管理员权限: group/group-setup.md
      - 群组管理功能:
          - 使用 ban、block 指令禁言或封禁成员和频道: group/ban.md
          - 使用 warn 指令警告成员和频道: group/warn.md
          - 使用 pin 指令置顶或取消置顶消息: group/pin.md
          - 自动识别并删除骚扰消息: group/anti-spam.md
          - 入群验证: group/join-verification.md
          - 关键词回复: group/key-word-reply.md
          - 同频气氛组: group/reply-channel.md
          - 操作记录: group/action-log.md
      - 群组娱乐功能:
          - banme: group/banme.md
          - pm Telegram 会员身份鉴定: group/is-premium.md
          - 群友互动: group/members-interaction.md
      - 频道透视眼: group/channel-perspective-eye.md
      - nmBot 群组功能所需权限说明: group/admin-rights-and-features.md
      - 在 nmBot 面板管理群组（若面板中找不到群组）: group/reg-panel.md
  - nmBot 面板:
      - 关于 nmBot 面板: about-panel.md
      - 启动 nmBot 面板: launch-panel.md
  - 设置 nmBot 语言: set-language.md
  - nmBot 积分:
      - 关于 nmBot 积分: credit/credit.md
  - nmartChat 智能聊天: nmartchat.md
  - nmBot 更新日志:
      - 2023 年 9 月: update-log/2023-09.md
      - 2023 年 8 月: update-log/2023-08.md
      - 2023 年 7 月: update-log/2023-07.md
      - 2023 年 6 月: update-log/2023-06.md
      - 2023 年 5 月: update-log/2023-05.md
      - 2023 年 4 月: update-log/2023-04.md
      - 2023 年 3 月: update-log/2023-03.md
      - 2023 年 2 月: update-log/2023-02.md
      - 2023 年 1 月: update-log/2023-01.md
      - update-log/previous-log.md
  - 条款和条件:
      - 使用条款: legal/terms-of-use.md
      - 隐私政策: legal/privacy-policy.md
  - 常见问题:
      - 如果您无法访问 nmBot 面板: faq/cannot-access-panel.md
      - 如果您无法在 nmBot 面板登录: faq/cannot-log-in-to-panel.md
      - 如果“频道验证”在您的群组中不工作: faq/channel-verification-not-working.md
      - nmBot /pm 指令提示“可能是 Telegram 会员”: faq/pm_might_be_premium.md
  - 更多帮助:
      - 关于 nmBot: about.md
      - 支持: support.md
